#!/usr/bin/env bash
# Configures my Nginx server so that /redirect_me is redirecting to another page.

REDIRECT_301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sudo sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default
sudo service nginx restart
