#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.

REDIRECT_301="\\\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;"
TEXT404_NOTFOUND="\n\\terror_page 404 /404.html;\n\tlocation = /var/www/html/404.html {\n\t\tinternal;\n\t}"
PATTERN="#error_page 404 /404.html;"

apt-get update
apt-get install -y nginx
echo "Hello World!" > /var/www/html/index.html
sed -i "30i $REDIRECT_301" /etc/nginx/sites-available/default
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i "47i\ $PATTERN$TEXT404_NOTFOUND" /etc/nginx/sites-available/default
service nginx restart
