#!/usr/bin/env bash
# Write a Bash script that displays To infinity and beyond indefinitely.
# In between each iteration of the loop, add a sleep 2

while true
do
	echo "To indinity and beyond"
	sleep 2
done
