#!/usr/bin/env bash
# A Bash script that prints "Best school" 10 times, but for the 9th iteration, displays Best School and then Hi on a new line.

i=1
while [ $i -le 10 ]
do
	if [ $i -eq 9 ]; then
		echo -e "BestSchool\nHi"
	else
		echo "BestSchool"
	fi
	((i++))
done
