#!/usr/bin/env bash
# Bash script that displays: The content of the current directory, In a list format, Where only the part of the name after the first dash is displayed.

for file in *; do
	if [[ -f "$file" && ! "$file" =~ ^\. ]]; then
		filename=$(echo "$file" | cut -d'-' -f2-)
		echo "$filename"
	fi
done
