#!/usr/bin/env bash
# This script configures this container to:
# 1. Run Nginx as nginx user
# 2. nginx must be listening on all active IPS on port 8080

# Create nginx user if it doesn't exist
if ! grep -q "^nginx:" /etc/passwd; then
    adduser --system --no-create-home --disabled-login --shell /bin/false nginx
fi

# Configure Nginx to run as nginx user
sed -i 's/^user\s*.\+;/user nginx;/g' /etc/nginx/nginx.conf

# Configure Nginx to listen on all IPs on port 8080
sed -i 's/listen\s*80;/listen 8080;/g' /etc/nginx/sites-available/default

# Restart Nginx for changes to take effect
service nginx restart
